sites:
  - path_site:        &path_site        "https://форум-трейдеров.рф/chart-online.php"
  - path_site_ctypto: &path_site_crypto "https://www.banknn.ru/kurs-kriptovalyut"
  - path_site_metal:  &path_site_metal  "https://cbr.ru/hd_base/metall/metall_base_new"


curs:
  - dollar:
    - link: *path_site
    - tag: "span"
    - catch: 11
    - signs: "n"

  - gold:
    - link: *path_site_metal
    - tag: "td"
    - catch: 2
    - signs: "y"

  - silver:
    - link: *path_site_metal
    - tag: "td"
    - catch: 3
    - signs: "y"

  - palladium:
    - link: *path_site_metal
    - tag: "td"
    - catch: 5
    - signs: "y"

  - bitcoin:
    - link: *path_site_crypto
    - tag: "td"
    - catch: 4
    - signs: "y"

  - ethereum:
    - link: *path_site_crypto
    - tag: "td"
    - catch: 9
    - signs: "y"
